version: '3'
services:



### DockPHPMySQL Management Container ##################################
  dockpsql:
    build:
      context: .
     # args:
     #   - PHP_UPSTREAM=php-fpm
    container_name: dockpsql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - "${DATA_SAVE_PATH}/mysql:/var/lib/mysql"
      - "${APPLICATION}:/var/www"
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
      - "${MYSQL_PORT}:3306"
    tty: true

    network_mode: "bridge"
